# Upload to production on Google Play
lane :production_release do 
  # Build the app bundle if you haven't already 
  gradle(task: 'bundleRelease')

  # Build the new AppBundle every time you run the lane
  sh("flutter clean")
  sh("flutter pub get")
  sh("flutter build appbundle --release")

  # Upload to production
  upload_to_play_store(
    track: 'production',  # Specify 'production' to release to the production track
    aab: '../build/app/outputs/bundle/release/app-release.aab',  # Update if your AAB path differs
    skip_upload_apk: true,
    skip_upload_images: true,  # Uncomment if you don't want to upload images
    skip_upload_screenshots: true,  # Uncomment if you don't want to upload screenshots
    skip_upload_metadata: true,  # Uncomment if you don't want to upload metadata
    skip_upload_changelogs: true,  # Uncomment if you don't want to upload changelogs
    skip_upload_aab: false

    # Uncomment the following line if using a service account (CI/CD)
    # service_account_json: 'path/to/your/service_account_key.json'
  )
end

lane :test do 
  # Build the app bundle if you haven't already 
  gradle(task: 'test')
end
