name: Build and Release
on:
  push:
    branches: 
      - master
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Kava
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'
      
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable' 
      
      - name: Install Dependencies
        run: flutter pub get
      
      - name: Build App Bundle
        run: |
          flutter build appbundle --release \
            --keystore="${{ secrets.KEYSTORE_FILE }}" \
            --keystore-password="${{ secrets.KEYSTORE_PASSWORD }}" \
            --key-alias="${{ secrets.KEY_ALIAS }}" \
            --key-password="${{ secrets.KEY_PASSWORD }}"

      - name: Upload App Bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/bundle/release/app-release.aab
    
      # - name: Use Keystore File
      #   run: |
      #         echo "${{ secrets.KEYSTORE_PASSWORD }}"
      #         echo "${{ secrets.KEY_PASSWORD }}"
      #         echo "${{ secrets.KEYSTORE_FILE }}"

        
      # - name: Build appBundle
      #   run: flutter build appbundle 

