name: Build and Deploy Android App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for Android builds

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Use the required JDK version

      - name: Install Fastlane
        run: |
          sudo gem install fastlane

      - name: Run Fastlane
        working-directory: android  # Set the working directory to android
        run: |
          fastlane build  # Replace 'build' with your lane name
