name: Build and Release
on:
  push:
    branches: 
      - master
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Kava
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'
      
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable' 
      
      - name: Install Dependencies
        run: flutter pub get    